<?php

/**
 * @file
 * Primary module hooks for CDI: Generate index ckeditor5 module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function cdi_generate_index_ckeditor5_preprocess_node(&$variables)
{
  $node_bundle = $variables['node']->bundle();

  if($node_bundle == 'rules_technical_rules' || $node_bundle == 'rules_technical_specifications'){
    $variables['#attached']['library'][] = 'cdi_generate_index_ckeditor5/cdi_generate_index_ckeditor5';
  }
}
